name: Integration and code analysis
on:
  workflow_dispatch: null
  push:
    branches:
      - main
      - master
      - develop
      - v1.1.0-preview.2
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Build-Test:
    name: Integration Test
    outputs:
      job-status: ${{ job.status }}
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven
        run: mvn install -DskipTests

      - name: Run tests with Maven
        run: mvn test

      - name: Run code coverage report
        run: mvn jacoco:report

      - name: Run code coverage check
        run: mvn clean verify

      - name: Publish test coverage results
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: 'target/site/jacoco/jacoco.xml'
          coverage_report_title: 'Test coverage results'
          coverage_report_name: 'Test coverage results'
          github_token: ${{ secrets.GITHUB_TOKEN }}

