# name: Deploy to Elastic Beanstalk

# on: [push]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Amazon Corretto 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'corretto'
#           cache: 'maven'

#       - name: Build and package with Maven
#         run: mvn package
#       - name: Print contents of target directory
#         run: ls target

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Upload package to S3
#         run: aws s3 cp target/answer-king-rest-api-0.0.1.jar s3://ans-java/answer-king-rest-api-0.0.1.jar

#       - name: Deploy to Elastic Beanstalk
#         run: |
#           aws elasticbeanstalk create-application-version --application-name ans-java-test --version-label my-app-${{ github.sha }} --source-bundle S3Bucket="ans-java",S3Key="answer-king-rest-api-0.0.1.jar"
#           aws elasticbeanstalk update-environment --environment-name Ansjavatest-env --version-label my-app-${{ github.sha }}

      # - name: Deploy to Elastic Beanstalk
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: eu-west-2
      #   run: |
      #     aws configure set region $AWS_REGION
      #     aws s3 cp target/answer-king-rest-api-0.0.1.jar s3://ans-java/answer-king-rest-api-0.0.1.jar
      #     aws elasticbeanstalk create-application-version --application-name ans-java-test --version-label my-app-${{ github.sha }} --source-bundle S3Bucket="ans-java",S3Key="answer-king-rest-api-0.0.1.jar"
      #     aws elasticbeanstalk update-environment --application-name ans-java-test --environment-name Ansjavatest-env --version-label my-app-${{ github.sha }}

name: Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/answer-king-rest-api-0.0.1.jar  
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: false
          application_name: answerKing-java
          environment_name: Answerkingjava-env
          version_label: ${{github.SHA}}
          region: eu-west-2
          deployment_package: answer-king-rest-api-0.0.1.jar  


# name: Deploy master
# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#     - name: Checkout source code
#       uses: actions/checkout@v2

#     - name: Generate deployment package
#       run: zip -r deploy.zip . -x '*.git*'

#     - name: Deploy to EB
#       uses: einaregilsson/beanstalk-deploy@v21
#       with:
#         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         application_name: ans-java-test
#         environment_name: Ansjavatest-env
#         version_label: 12345
#         region: us-east-1
#         deployment_package: deploy.zip